### ISSUE TITLE
AttributeError: Can't pickle local object 'dbfy_mp.<locals>._pool_init'

### ISSUE THREAD

**Issue by kvasnyj** [kaniblu/wiki-mysql#1]
Hello,
Could you help me please with the error:

```
Parsing and storing articles to mysql...
Traceback (most recent call last):
  File "c:\Users\kvasn\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\kvasn\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\kvasn\.vscode\extensions\ms-python.python-2019.5.18875\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Repo\wiki-mysql\dbfy.py", line 317, in <module>
    main()
  File "c:\Repo\wiki-mysql\dbfy.py", line 308, in main
    dbfy_fn(dmp_path, db_init, fltr_init, n_processes=n_processes, limit=limit)
  File "c:\Repo\wiki-mysql\dbfy.py", line 225, in dbfy_mp
    pool = mp.Pool(n_processes, _pool_init, (db_init, fltr_init))
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\kvasn\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'dbfy_mp.<locals>._pool_init'
```

**Comment by kaniblu** [comment]
I haven't tested the code on Windows, so it might be caused by python failing to pickle local functions on Windows. I suggest working around the problem by moving the local function `_pool_init` to the global context (above the declaration of `dbfy_mp`).
